name: CI-TESTES-API-JOAB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run postman/Serverest.postman_collection.json \
            --environment postman/Serverest.postman_environment.json \
            --reporters cli,junit,html \
            --reporter-junit-export "newman-report.xml" \
            --reporter-html-export "newman-report.html"
            
      - name: Upload JUnit Test Results
        uses: actions/upload-artifact@v3.1.1
        with:
          name: newman-junit-report
          path: newman-report.xml

      - name: Upload HTML Test Results
        uses: actions/upload-artifact@v3.1.1
        with:
          name: newman-html-report
          path: newman-report.html
